/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardLiveRouteImport } from './routes/dashboard-live'
import { Route as CaptainsRouteImport } from './routes/captains'
import { Route as ArchiveGalleryRouteImport } from './routes/archive-gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminParticipantsRouteImport } from './routes/admin/participants'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminHousesRouteImport } from './routes/admin/houses'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/dashboard-live',
  path: '/dashboard-live',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsRoute = CaptainsRouteImport.update({
  id: '/captains',
  path: '/captains',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveGalleryRoute = ArchiveGalleryRouteImport.update({
  id: '/archive-gallery',
  path: '/archive-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/admin/leaderboard',
  path: '/admin/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHousesRoute = AdminHousesRouteImport.update({
  id: '/admin/houses',
  path: '/admin/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive-gallery': typeof ArchiveGalleryRoute
  '/captains': typeof CaptainsRoute
  '/dashboard-live': typeof DashboardLiveRoute
  '/events': typeof EventsRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/houses': typeof AdminHousesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive-gallery': typeof ArchiveGalleryRoute
  '/captains': typeof CaptainsRoute
  '/dashboard-live': typeof DashboardLiveRoute
  '/events': typeof EventsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/houses': typeof AdminHousesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive-gallery': typeof ArchiveGalleryRoute
  '/captains': typeof CaptainsRoute
  '/dashboard-live': typeof DashboardLiveRoute
  '/events': typeof EventsRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/houses': typeof AdminHousesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive-gallery'
    | '/captains'
    | '/dashboard-live'
    | '/events'
    | '/admin'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive-gallery'
    | '/captains'
    | '/dashboard-live'
    | '/events'
    | '/admin'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/archive-gallery'
    | '/captains'
    | '/dashboard-live'
    | '/events'
    | '/admin/_layout'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveGalleryRoute: typeof ArchiveGalleryRoute
  CaptainsRoute: typeof CaptainsRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  EventsRoute: typeof EventsRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHousesRoute: typeof AdminHousesRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-live': {
      id: '/dashboard-live'
      path: '/dashboard-live'
      fullPath: '/dashboard-live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains': {
      id: '/captains'
      path: '/captains'
      fullPath: '/captains'
      preLoaderRoute: typeof CaptainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive-gallery': {
      id: '/archive-gallery'
      path: '/archive-gallery'
      fullPath: '/archive-gallery'
      preLoaderRoute: typeof ArchiveGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/houses': {
      id: '/admin/houses'
      path: '/admin/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AdminHousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveGalleryRoute: ArchiveGalleryRoute,
  CaptainsRoute: CaptainsRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  EventsRoute: EventsRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHousesRoute: AdminHousesRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
